import { readFileSync, writeFileSync } from 'fs';

const TAGS = {
  1: ["Science & Space"],
  2: ["Science & Space"],
  3: ["Science & Space"],
  4: ["Science & Space"],
  5: ["Science & Space"],
  6: ["Science & Space"],
  7: ["Science & Space"],
  8: ["Science & Space"],
  9: ["Science & Space"],
  10: ["Technology & AI"],
  11: ["World History"],
  12: ["World History"],
  13: ["World History"],
  14: ["World History"],
  15: ["World History"],
  16: ["World History"],
  17: ["World History"],
  18: ["World History"],
  19: ["World History"],
  20: ["World History"],
  21: ["Geography & Earth"],
  22: ["Geography & Earth"],
  23: ["Geography & Earth"],
  24: ["Geography & Earth"],
  25: ["Geography & Earth"],
  26: ["Geography & Earth"],
  27: ["Geography & Earth"],
  28: ["Geography & Earth"],
  29: ["Psychology & Mind"],
  30: ["Psychology & Mind", "Economics & Money"],
  31: ["Psychology & Mind"],
  32: ["Psychology & Mind"],
  33: ["Psychology & Mind"],
  34: ["Psychology & Mind"],
  35: ["Psychology & Mind"],
  36: ["Science & Space"],
  37: ["Science & Space"],
  38: ["Science & Space"],
  39: ["Science & Space"],
  40: ["Science & Space"],
  41: ["Science & Space"],
  42: ["Science & Space"],
  43: ["Science & Space"],
  44: ["Nature & Environment"],
  45: ["Nature & Environment"],
  46: ["Nature & Environment"],
  47: ["Nature & Environment"],
  48: ["Nature & Environment"],
  49: ["Nature & Environment"],
  50: ["Nature & Environment"],
  51: ["Nature & Environment"],
  52: ["Nature & Environment"],
  53: ["Nature & Environment"],
  54: ["Nature & Environment"],
  55: ["Nature & Environment"],
  56: ["Nature & Environment"],
  57: ["Nature & Environment"],
  58: ["Current Affairs", "Indian History & Culture"],
  59: ["Current Affairs", "Technology & AI"],
  60: ["Current Affairs"],
  61: ["Current Affairs", "Nature & Environment"],
  62: ["Current Affairs", "Nature & Environment"],
  63: ["Current Affairs"],
  64: ["Current Affairs"],
  65: ["Current Affairs"],
  66: ["Current Affairs"],
  67: ["Psychology & Mind"],
  68: ["Arts & Culture"],
  69: ["Arts & Culture"],
  70: ["Arts & Culture"],
  71: ["Arts & Culture"],
  72: ["Arts & Culture"],
  73: ["Arts & Culture"],
  74: ["Arts & Culture"],
  75: ["Arts & Culture"],
  76: ["Arts & Culture"],
  77: ["Arts & Culture"],
  78: ["Arts & Culture"],
  79: ["Arts & Culture"],
  80: ["Arts & Culture"],
  81: ["Arts & Culture"],
  82: ["Philosophy & Ideas"],
  83: ["Philosophy & Ideas"],
  84: ["Philosophy & Ideas", "Nature & Environment"],
  85: ["Philosophy & Ideas"],
  86: ["Arts & Culture"],
  87: ["Arts & Culture"],
  88: ["Nature & Environment"],
  89: ["Economics & Money"],
  90: ["Economics & Money"],
  91: ["Economics & Money"],
  92: ["Economics & Money"],
  93: ["Economics & Money"],
  94: ["Economics & Money"],
  95: ["Food & Culture"],
  96: ["Food & Culture", "World History"],
  97: ["Food & Culture"],
  98: ["Food & Culture"],
  99: ["Food & Culture"],
  100: ["Food & Culture"],
};

let content = readFileSync('src/App.jsx', 'utf8');

for (const [id, tags] of Object.entries(TAGS)) {
  const tagStr = JSON.stringify(tags).replace(/"/g, '"');
  // Match {id:N, at the start of each article object — insert tags after id
  const pattern = new RegExp(`(\\{id:${id},)`, 'g');
  content = content.replace(pattern, `$1tags:${tagStr},`);
}

writeFileSync('src/App.jsx', content, 'utf8');
console.log('Tags added to all 100 articles.');
